-- This file contains the MySQL DDL for inserting some initial entries into the tables.
-- You do not need to use this: you can start with a blank slate if desired.
-- If you do want to use this, then copy and paste this entire file into MySQL Workbench.
--
-- NOTE: Currently being used for testing, not final.

---------------------- Users ----------------------
INSERT INTO users (username, email, password, is_mod) VALUES ('leucine', 'leucine1@gmail.com', '0leuc0', 0);
INSERT INTO users (username, email, password, is_mod) VALUES ('desuMod', 'deshita@yahoo.com', 'desu', 1);
INSERT INTO users (username, email, password, is_mod) VALUES ('KamiSama', 'ks@gmail.com', 'kamisama', 0);
INSERT INTO users (username, email, password, is_mod) VALUES ('ogey', 'ogey@rrat.net', 'rratchama', 0);
INSERT INTO users (username, email, password, is_mod) VALUES ('rrat', 'rrat@ogey.org', 'ogey', 1);
INSERT INTO users (username, email, password, is_mod) VALUES ('TRYPTOPHAN', 'hmm@mmm.mmm', 'sus', 0);
INSERT INTO users (username, email, password, is_mod) VALUES ('naruhodone', 'nene@nene.ne', 'BakaYarou', 0);
INSERT INTO users (username, email, password, is_mod) VALUES ('Chama', 'sou@desu.ka', 'pepeloni1', 1);

---------------------- Boards ----------------------
INSERT INTO boards (short_name, name, description, user_id) VALUES ('v', 'Video Games', 'Discuss.', NULL);
INSERT INTO boards (short_name, name, description, user_id) VALUES ('a', 'Anime', 'No western cartoons.', 5);
INSERT INTO boards (short_name, name, description, user_id) VALUES ('g', 'Technology', NULL, 8);
INSERT INTO boards (short_name, name, description, user_id) VALUES ('vt', 'Virtual Youtubers', 'peko', 8);
INSERT INTO boards (short_name, name, description, user_id) VALUES ('tv', 'Television', 'RIP Netflix', 8);
INSERT INTO boards (short_name, name, description, user_id) VALUES ('mu', 'Music', NULL, NULL);
INSERT INTO boards (short_name, name, description, user_id) VALUES ('rel', 'Religion', 'All are welcome!', 5);

---------------------- Threads ----------------------
-- (will be removed later since the paths are randomly generated by the server)
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('Tatami Galaxy', 'Discuss.', '/path/to/t_img1.png', '/path/to/th-t_img1.png', 'pain.png', 2, NULL);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('LiSA Thread', NULL, '/path/to/t_img2.jpg', '/path/to/th-t_img2.jpg', 'lisa_live.jpg', 6, 6);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('Favourite VGM?', 'Please no links', '/path/to/t_img3.jpg', '/path/to/th-t_img3.jpg', 'thonk.jpg', 6, 2);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES (NULL, NULL, '/path/to/t_img4.jpg', '/path/to/th-t_img4.jpg', 'smug_anime_girl.jpg', 2, 8);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES (NULL, 'See you, space cowboy.', '/path/to/t_img5.png', '/path/to/th-t_img5.png', 'bepis.png', 2, 8);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('Hololive General', 'Ina love!', '/path/to/t_img6.jpg', '/path/to/th-t_img6.jpg', 'ina.jpg', 4, NULL);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('Nijisanji General', 'Ina hate!', '/path/to/t_img7.png', '/path/to/th-t_img7.png', 'not_ina.png', 4, 6);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('Netflix Recommendations', 'pls', '/path/to/t_img8.jpg', '/path/to/th-t_img8.jpg', 'sad_pepe.jpg', 5, 8);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES (NULL, NULL, '/path/to/t_img9.jpg', '/path/to/th-t_img9.jpg', 'bill_gates.jpg', 3, NULL);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('Roguelikes/lites', 'Rogue Legacy 2 is out!', '/path/to/t_img10.png', '/path/to/th-t_img10.png', 'backslash.png', 1, 3);
INSERT INTO threads (subject, body, image_path, thumbnail_path, orig_filename, board_id, user_id)
VALUES ('honk honk', '2hu music thread', '/path/to/t_img11.png', '/path/to/th-t_img11.png', 'chen.png', 6, NULL);

---------------------- Replies ----------------------
-- (will be removed later since the paths are randomly generated by the server)
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('Trisection from Final Fantasy Tactics is great.', '/path/to/r_img1.jpg', '/path/to/th-r_img1.jpg', 'ramza.jpg', 3, NULL);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('YUME DE TAKAKU TONDA KARADA WA', '/path/to/r_img2.jpg', '/path/to/th-r_img2.jpg', 'shion.jpg', 2, 1);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('Did Ina play Minecraft yet?', NULL, NULL, NULL, 6, 8);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('@3 Yes, she has.', NULL, NULL, NULL, 6, 7);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('Ina hate!!', '/path/to/r_img3.jpg', '/path/to/th-r_img3.jpg', 'sad_ina.jpg', 7, 1);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('@2 ayo?', '/path/to/r_img4.png', '/path/to/th-r_img4.png', 'giant_blushing_emoji.png', 2, NULL);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('Ina hate!!', NULL, NULL, NULL, 6, 1);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('@3 Where have you been?', NULL, NULL, NULL, 6, NULL);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('Whens the next OP dropping?', NULL, NULL, NULL, 2, 6);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('@1 agreed', NULL, NULL, NULL, 3, NULL);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ('Parasyte?', NULL, NULL, NULL, 8, 1);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ("@11 I've already seen it :(", '/path/to/r_img5.jpg', '/path/to/th-r_img5.jpg', 'sadge.jpg', 8, 8);
INSERT INTO replies (reply, image_path, thumbnail_path, orig_filename, thread_id, user_id)
VALUES ("tutturu~", NULL, NULL, NULL, 5, NULL);

---------------------- Bookmarks ----------------------
-- (will be removed later since the initial threads will be deleted later)
INSERT INTO bookmarks (user_id, thread_id) VALUES (1, 3);
INSERT INTO bookmarks (user_id, thread_id) VALUES (1, 9);
INSERT INTO bookmarks (user_id, thread_id) VALUES (1, 4);
INSERT INTO bookmarks (user_id, thread_id) VALUES (1, 1);
INSERT INTO bookmarks (user_id, thread_id) VALUES (2, 3);
INSERT INTO bookmarks (user_id, thread_id) VALUES (7, 4);
INSERT INTO bookmarks (user_id, thread_id) VALUES (7, 5);
INSERT INTO bookmarks (user_id, thread_id) VALUES (3, 3);